apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-gitops-flux
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-gitops-flux
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Crossplane configuration is a starting point to use gitops in your own internal cloud.
    meta.crossplane.io/readme: |
      This Crossplane configuration is a starting point to use gitops in your own internal cloud.
      To learn more checkout the [GitHub repo](https://github.com/upbound/configuration-gitops-flux/)
      that you can copy and customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.13.2-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.15.0"
