apiVersion: gitops.platform.upbound.io/v1alpha1
kind: Flux
metadata:
  name: configuration-gitops-flux
  namespace: default
spec:
  parameters:
    providerConfigName: configuration-gitops-flux
    managementPolicies: ["*"]
    operators:
      flux:
        version: "2.10.6"
      fluxSync:
        version: "1.7.2"
    source:
      git:
        url: https://github.com/upbound/platform-ref-aws/
        ref:
          name: refs/heads/main
        interval: "5m0s"
        timeout: "60s"
        path: "/"
