apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: flux.gitops.platform.upbound.io
spec:
  scope: Namespaced
  group: gitops.platform.upbound.io
  names:
    kind: Flux
    plural: flux
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Flux configuration parameters.
                  properties:
                    providerConfigName:
                      type: string
                      description: Crossplane ProviderConfig to use for provisioning this resources
                    managementPolicies:
                      description: ManagementPolicies for the Helm resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                      default: ["*"]
                    kubeConfigSecretRef:
                      description: The KubeConfig for reconciling the Kustomization on a remote cluster. In v2, namespace is inferred from the resource namespace.
                      type: object
                      properties:
                        name:
                          description: Name of the Secret
                          type: string
                        key:
                          description: Key in the Secret
                          type: string
                          default: kubeconfig
                    operators:
                      description: Configuration for operators.
                      type: object
                      default:
                        flux:
                          version: "2.10.6"
                        fluxSync:
                          version: "1.7.2"
                      properties:
                        flux:
                          description: Configuration for the Flux GitOps operator.
                          type: object
                          properties:
                            version:
                              description: flux helm-chart version to run.
                              type: string
                              default: "2.10.6"
                          required:
                            - version
                        fluxSync:
                          description: Configuration for the Flux Sync Helm-Chart.
                          type: object
                          properties:
                            version:
                              description: flux sync helm-chart version to run.
                              type: string
                              default: "1.7.2"
                          required:
                            - version
                    source:
                      type: object
                      properties:
                        git:
                          type: object
                          properties:
                            interval:
                              default: "5m0s"
                              description: Interval at which the GitRepository URL is checked for
                                updates. This interval is approximate and may be subject to jitter
                                to ensure efficient use of resources.
                              pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                              type: string
                            timeout:
                              default: "60s"
                              description: Timeout for Git operations like cloning, defaults to
                                60s.
                              pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m))+$
                              type: string
                            url:
                              description: URL specifies the Git repository URL, it can be an HTTP/S
                                or SSH address.
                              pattern: ^(http|https|ssh)://.*$
                              type: string
                            path:
                              type: string
                              default: "/"
                            ref:
                              description: Reference specifies the Git reference to resolve and
                                monitor for changes.
                              type: object
                              properties:
                                name:
                                  description: "Name of the reference to check out; takes precedence
                                    over Branch, Tag and SemVer. \n It must be a valid Git reference:
                                    https://git-scm.com/docs/git-check-ref-format#_description Examples:
                                    \"refs/heads/main\", \"refs/tags/v0.1.0\", \"refs/pull/420/head\",
                                    \"refs/merge-requests/1/head\""
                                  type: string
                          required:
                            - interval
                            - timeout
                            - url
                            - path
                            - ref
                      required:
                        - git
                  required:
                    - providerConfigName
                    - managementPolicies
                    - source
