name: yamllint
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: yamllint
        uses: reviewdog/action-yamllint@5dd4640db975e4cac6f4e775a401695bafc28068 # v1.25.1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          yamllint_flags: 'apis/'
          fail_on_error: true
